### ISSUE TITLE
Consider using NoSuspend

### ISSUE THREAD

**Issue by KOLANICH** [ComputationalSystemsBiology/BCMLtoSBMLconverter#1]
https://github.com/KOLANICH/NoSuspend.py/blob/master/NoSuspend.py

**Comment by chernan** [comment]
Thanks for your suggestion but this tool doesn't run long enough to need this.

**Comment by KOLANICH** [comment]
Oh, sorry for the disturbance, your project really doesn't use this kind of `Inhibit`ion.
